In [2]:
import pandas as pd
import os

# Pasta onde serão salvos os CSVs filtrados
pasta_saida = "/content/sample_data/matriculados"

os.makedirs(pasta_saida, exist_ok=True)

municipios_alvo = [
    'MARICÁ',
    'NITERÓI',
    'RIO DE JANEIRO',
    'SÃO GONÇALO'
]

colunas_necessarias = [
    'NU_ANO_CENSO',
    'NO_MUNICIPIO',
    'CO_ENTIDADE',
    'NO_ENTIDADE',
    'TP_DEPENDENCIA',
    'QT_MAT_MED'
]

def filtrar_matriculados(ano):

    if ano == 2025:
        arquivo = 'Tabela_Matricula_2025_V2.csv'
    else:
        arquivo = f'microdados_ed_basica_{ano}.csv'

    df = pd.read_csv(
        arquivo,
        sep=';',
        encoding='latin1',
        usecols=colunas_necessarias,
        low_memory=False
    )

    # Padroniza os nomes dos municípios
    df['NO_MUNICIPIO'] = (
        df['NO_MUNICIPIO']
        .astype(str)
        .str.strip()
        .str.upper()
    )

    # Aplicação dos filtros
    df_filtrado = df[
        (df['TP_DEPENDENCIA'] == 2) &
        (df['NO_MUNICIPIO'].isin(municipios_alvo)) &
        (df['QT_MAT_MED'] > 0)
    ].copy()

    # Renomeia as colunas
    df_filtrado = df_filtrado.rename(columns={
        'NU_ANO_CENSO': 'Ano do Censo',
        'NO_MUNICIPIO': 'Nome do Município',
        'CO_ENTIDADE': 'Código da Escola',
        'NO_ENTIDADE': 'Nome da Escola',
        'TP_DEPENDENCIA': 'Dependência Administrativa',
        'QT_MAT_MED': 'Quantidade de Matriculados Ensino Médio'
    })

    # Nome do arquivo de saída
    saida = f'{pasta_saida}/Matriculados{ano}ano.csv'

    df_filtrado.to_csv(
        saida,
        index=False,
        encoding='utf-8-sig'
    )

    print(f'Ano {ano}: {len(df_filtrado)} registros encontrados.')
    print(f'Arquivo salvo em: {saida}')

    return df_filtrado

# ANO 2015

In [ ]:
df_2015 = filtrar_matriculados(2015)

display(df_2015.head())

Ano 2015: 365 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2015ano.csv

,Ano do Censo,Nome do Município,Código da Escola,Nome da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
154228,2015,MARICÁ,33053910,CE ELISIARIO MATTA,2,777
154231,2015,MARICÁ,33053952,CE DOMICIO DA GAMA,2,377
154248,2015,MARICÁ,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,2,516
154249,2015,MARICÁ,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,2,400
154251,2015,MARICÁ,33054215,CE EUCLYDES PAULO DA SILVA,2,211

# ANO 2016

In [ ]:
df_2016 = filtrar_matriculados(2016)

display(df_2016.head())

Ano 2016: 364 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2016ano.csv

,Ano do Censo,Nome do Município,Código da Escola,Nome da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
153793,2016,MARICÁ,33053910,CE ELISIARIO MATTA,2,721
153796,2016,MARICÁ,33053952,CE DOMICIO DA GAMA,2,408
153811,2016,MARICÁ,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,2,570
153812,2016,MARICÁ,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,2,325
153814,2016,MARICÁ,33054215,CE EUCLYDES PAULO DA SILVA,2,204

# ANO 2017

In [ ]:
df_2017 = filtrar_matriculados(2017)

display(df_2017.head())

Ano 2017: 370 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2017ano.csv

,Ano do Censo,Nome do Município,Código da Escola,Nome da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
152609,2017,MARICÁ,33053910,CE ELISIARIO MATTA,2,780
152612,2017,MARICÁ,33053952,CE DOMICIO DA GAMA,2,305
152614,2017,MARICÁ,33053995,CE PROFESSORA CACILDA SILVA,2,28
152627,2017,MARICÁ,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,2,506
152628,2017,MARICÁ,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,2,336

# ANO 2018

In [ ]:
df_2018 = filtrar_matriculados(2018)

display(df_2018.head())

Ano 2018: 370 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2018ano.csv

,Ano do Censo,Nome do Município,Código da Escola,Nome da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
151859,2018,MARICÁ,33053910,CE ELISIARIO MATTA,2,870
151862,2018,MARICÁ,33053952,CE DOMICIO DA GAMA,2,314
151864,2018,MARICÁ,33053995,CE PROFESSORA CACILDA SILVA,2,102
151876,2018,MARICÁ,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,2,577
151877,2018,MARICÁ,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,2,341

# ANO 2019

In [ ]:
df_2019 = filtrar_matriculados(2019)

display(df_2019.head())

Ano 2019: 360 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2019ano.csv

,Ano do Censo,Nome do Município,Código da Escola,Nome da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
144583,2019,MARICÁ,33053910,CE ELISIARIO MATTA,2,1047
144586,2019,MARICÁ,33053952,CE DOMICIO DA GAMA,2,382
144588,2019,MARICÁ,33053995,CE PROFESSORA CACILDA SILVA,2,161
144600,2019,MARICÁ,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,2,611
144601,2019,MARICÁ,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,2,388

#ANO 2020

In [ ]:
df_2020 = filtrar_matriculados(2020)

display(df_2020.head())

Ano 2020: 363 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2020ano.csv

,Ano do Censo,Nome do Município,Código da Escola,Nome da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
140465,2020,MARICÁ,33053910,CE ELISIARIO MATTA,2,1042
140468,2020,MARICÁ,33053952,CE DOMICIO DA GAMA,2,406
140470,2020,MARICÁ,33053995,CE PROFESSORA CACILDA SILVA,2,163
140482,2020,MARICÁ,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,2,640
140483,2020,MARICÁ,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,2,496

# ANO 2021

In [ ]:
df_2021 = filtrar_matriculados(2021)

display(df_2021.head())

Ano 2021: 363 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2021ano.csv

,Ano do Censo,Nome do Município,Código da Escola,Nome da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
137128,2021,MARICÁ,33053910,CE ELISIARIO MATTA,2,1003
137131,2021,MARICÁ,33053952,CE DOMICIO DA GAMA,2,406
137133,2021,MARICÁ,33053995,CE PROFESSORA CACILDA SILVA,2,178
137145,2021,MARICÁ,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,2,640
137146,2021,MARICÁ,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,2,592

# ANO 2022

In [ ]:
df_2022 = filtrar_matriculados(2022)

display(df_2022.head())

Ano 2022: 363 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2022ano.csv

,Ano do Censo,Nome do Município,Nome da Escola,Código da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
139417,2022,MARICÁ,CE ELISIARIO MATTA,33053910,2,1062.0
139420,2022,MARICÁ,CE DOMICIO DA GAMA,33053952,2,419.0
139422,2022,MARICÁ,CE PROFESSORA CACILDA SILVA,33053995,2,146.0
139434,2022,MARICÁ,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,33054177,2,630.0
139435,2022,MARICÁ,CE CAIO FRANCISCO DE FIGUEIREDO,33054185,2,599.0

# ANO 2023

In [ ]:
df_2023 = filtrar_matriculados(2023)

display(df_2023.head())

Ano 2023: 364 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2023ano.csv

,Ano do Censo,Nome do Município,Nome da Escola,Código da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
133457,2023,SÃO GONÇALO,CE DOUTOR MOACYR MEIRELLES PADILHA,33051879,2,333.0
133604,2023,MARICÁ,CE ELISIARIO MATTA,33053910,2,1205.0
133607,2023,MARICÁ,CE DOMICIO DA GAMA,33053952,2,411.0
133609,2023,MARICÁ,CE PROFESSORA CACILDA SILVA,33053995,2,142.0
133621,2023,MARICÁ,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,33054177,2,606.0

# ANO 2024

In [ ]:
df_2024 = filtrar_matriculados(2024)

display(df_2024.head())

Ano 2024: 368 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2024ano.csv

,Ano do Censo,Nome do Município,Nome da Escola,Código da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
132165,2024,MARICÁ,CE ELISIARIO MATTA,33053910,2,1373.0
132168,2024,MARICÁ,CE DOMICIO DA GAMA,33053952,2,390.0
132170,2024,MARICÁ,CE PROFESSORA CACILDA SILVA,33053995,2,170.0
132183,2024,MARICÁ,CE FRANCISCO JOSE DO NASCIMENTO,33054339,2,390.0
132190,2024,MARICÁ,CIEP 259 PROFESSORA MARIA DO AMPARO RANGEL DE ...,33102414,2,1387.0

# ANO 2025

In [3]:
df_2025 = filtrar_matriculados(2025)

display(df_2025.head())

Ano 2025: 368 registros encontrados.
Arquivo salvo em: /content/sample_data/matriculados/Matriculados2025ano.csv

,Ano do Censo,Nome do Município,Nome da Escola,Código da Escola,Dependência Administrativa,Quantidade de Matriculados Ensino Médio
103647,2025,MARICÁ,CE ELISIARIO MATTA,33053910,2,1443
103650,2025,MARICÁ,CE DOMICIO DA GAMA,33053952,2,381
103651,2025,MARICÁ,CE PROFESSORA CACILDA SILVA,33053995,2,152
103670,2025,MARICÁ,CIEP 259 PROFESSORA MARIA DO AMPARO RANGEL DE ...,33102414,2,1382
103697,2025,MARICÁ,CE PROFESSOR DARCY RIBEIRO,33183562,2,1601

# CONCAT

In [4]:
import glob
import pandas as pd

# Pega somente os arquivos anuais de matriculados
pasta = "/content/sample_data/matriculados/Matriculados*ano.csv"

arquivos = sorted(glob.glob(pasta))

print(f"{len(arquivos)} arquivos encontrados:")
for arquivo in arquivos:
    print(arquivo)

if len(arquivos) > 0:

    df_final = pd.concat(
        [pd.read_csv(arquivo) for arquivo in arquivos],
        ignore_index=True
    )

    # Organiza a tabela
    df_final = df_final.sort_values(
        by=[
            'Ano do Censo',
            'Nome do Município',
            'Nome da Escola'
        ]
    ).reset_index(drop=True)

    print("\nConcatenação e ordenação concluídas!")
    print(f"Total de registros: {len(df_final)}")

else:
    print("Nenhum arquivo encontrado. Verifique o caminho.")

1 arquivos encontrados:
/content/sample_data/matriculados/Matriculados2025ano.csv

Concatenação e ordenação concluídas!
Total de registros: 368

In [5]:
arquivo_concatenado = "/content/sample_data/matriculados/matriculados_concatenados.csv"

df_final.to_csv(
    arquivo_concatenado,
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo criado com sucesso!")
print(arquivo_concatenado)

Arquivo criado com sucesso!
/content/sample_data/matriculados/matriculados_concatenados.csv

In [9]:
import pandas as pd

matriculados = pd.read_csv(
    "/content/sample_data/matriculados/matriculados_concatenados.csv"
)

print(sorted(matriculados["Ano do Censo"].unique()))

[np.int64(2025)]

# JOIN Matriculados + Rendimentos

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

for raiz, pastas, arquivos in os.walk('/content/drive/MyDrive'):
    for arquivo in arquivos:
        if arquivo in [
            'matriculados_concatenados.csv',
            'rendimentos_concatenados.csv'
        ]:
            print(os.path.join(raiz, arquivo))

/content/drive/MyDrive/rendimentos_concatenados.csv
/content/drive/MyDrive/matriculados_concatenados.csv

In [ ]:
import pandas as pd

matriculados = pd.read_csv(
    "/content/drive/MyDrive/matriculados_concatenados.csv"
)

rendimentos = pd.read_csv(
    "/content/drive/MyDrive/rendimentos_concatenados.csv"
)

print("COLUNAS MATRICULADOS:")
print(matriculados.columns.tolist())

print("\nCOLUNAS RENDIMENTOS:")
print(rendimentos.columns.tolist())

COLUNAS MATRICULADOS:
['Ano do Censo', 'Nome do Município', 'Código da Escola', 'Nome da Escola', 'Dependência Administrativa', 'Quantidade de Matriculados Ensino Médio']

COLUNAS RENDIMENTOS:
['Ano', 'Municipio', 'Codigo_Escola', 'Escola', 'Dependencia', 'Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

In [ ]:
import unicodedata
import re

def normalizar_coluna(nome):
    # Remove acentos
    nome = unicodedata.normalize('NFKD', str(nome))
    nome = nome.encode('ascii', 'ignore').decode('ascii')

    # Remove espaços nas pontas
    nome = nome.strip()

    # Troca espaços por _
    nome = nome.replace(' ', '_')

    # Remove caracteres estranhos
    nome = re.sub(r'[^A-Za-z0-9_]', '', nome)

    return nome


# Padroniza todas as colunas
matriculados.columns = [
    normalizar_coluna(c) for c in matriculados.columns
]

rendimentos.columns = [
    normalizar_coluna(c) for c in rendimentos.columns
]

print("MATRICULADOS:")
print(matriculados.columns.tolist())

print("\nRENDIMENTOS:")
print(rendimentos.columns.tolist())

MATRICULADOS:
['Ano_do_Censo', 'Nome_do_Municipio', 'Codigo_da_Escola', 'Nome_da_Escola', 'Dependencia_Administrativa', 'Quantidade_de_Matriculados_Ensino_Medio']

RENDIMENTOS:
['Ano', 'Municipio', 'Codigo_Escola', 'Escola', 'Dependencia', 'Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

In [ ]:
matriculados['Codigo_da_Escola'] = pd.to_numeric(
    matriculados['Codigo_da_Escola'],
    errors='coerce'
).astype('Int64')

rendimentos['Codigo_Escola'] = pd.to_numeric(
    rendimentos['Codigo_Escola'],
    errors='coerce'
).astype('Int64')

matriculados['Ano_do_Censo'] = pd.to_numeric(
    matriculados['Ano_do_Censo'],
    errors='coerce'
).astype('Int64')

rendimentos['Ano'] = pd.to_numeric(
    rendimentos['Ano'],
    errors='coerce'
).astype('Int64')

print("Tipos padronizados com sucesso!")

Tipos padronizados com sucesso!

In [ ]:
duplicados_matriculados = matriculados.duplicated(
    subset=['Codigo_da_Escola', 'Ano_do_Censo']
).sum()

duplicados_rendimentos = rendimentos.duplicated(
    subset=['Codigo_Escola', 'Ano']
).sum()

print("Duplicados em Matriculados:", duplicados_matriculados)
print("Duplicados em Rendimentos:", duplicados_rendimentos)

Duplicados em Matriculados: 0
Duplicados em Rendimentos: 0

In [ ]:
df_join = pd.merge(
    matriculados,
    rendimentos,
    left_on=['Codigo_da_Escola', 'Ano_do_Censo'],
    right_on=['Codigo_Escola', 'Ano'],
    how='inner'
)

print("JOIN concluído!")
print("Matriculados:", len(matriculados))
print("Rendimentos:", len(rendimentos))
print("Resultado do JOIN:", len(df_join))

display(df_join.head())

JOIN concluído!
Matriculados: 3650
Rendimentos: 4009
Resultado do JOIN: 3641

,Ano_do_Censo,Nome_do_Municipio,Codigo_da_Escola,Nome_da_Escola,Dependencia_Administrativa,Quantidade_de_Matriculados_Ensino_Medio,Ano,Municipio,Codigo_Escola,Escola,Dependencia,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
0,2015,MARICÁ,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,2,400.0,2015,Maricá,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,Estadual,86.6,9.1,4.3
1,2015,MARICÁ,33053952,CE DOMICIO DA GAMA,2,377.0,2015,Maricá,33053952,CE DOMICIO DA GAMA,Estadual,78.1,17.7,4.2
2,2015,MARICÁ,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,2,516.0,2015,Maricá,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,Estadual,87.2,8.8,4.0
3,2015,MARICÁ,33053910,CE ELISIARIO MATTA,2,777.0,2015,Maricá,33053910,CE ELISIARIO MATTA,Estadual,89.3,10.3,0.4
4,2015,MARICÁ,33054215,CE EUCLYDES PAULO DA SILVA,2,211.0,2015,Maricá,33054215,CE EUCLYDES PAULO DA SILVA,Estadual,72.2,21.7,6.1

In [ ]:
nao_encontrados = matriculados.merge(
    rendimentos,
    left_on=['Codigo_da_Escola', 'Ano_do_Censo'],
    right_on=['Codigo_Escola', 'Ano'],
    how='left',
    indicator=True
)

nao_encontrados = nao_encontrados[
    nao_encontrados['_merge'] == 'left_only'
]

display(
    nao_encontrados[
        [
            'Ano_do_Censo',
            'Nome_do_Municipio',
            'Codigo_da_Escola',
            'Nome_da_Escola'
        ]
    ]
)

,Ano_do_Censo,Nome_do_Municipio,Codigo_da_Escola,Nome_da_Escola
155,2015,RIO DE JANEIRO,33111626,CE LUIZA MAHIN
188,2015,RIO DE JANEIRO,33124620,CE PADRE CARLOS LEONCIO DA SILVA
551,2016,RIO DE JANEIRO,33124620,CE PADRE CARLOS LEONCIO DA SILVA
656,2016,RIO DE JANEIRO,33076480,E T E REPUBLICA
659,2016,RIO DE JANEIRO,33075034,ESCOLA TECNICA ESTADUAL OSCAR TENORIO
661,2016,RIO DE JANEIRO,33076502,ESCOLA TECNICA ESTADUAL VISCONDE DE MAUA
918,2017,RIO DE JANEIRO,33124620,CE PADRE CARLOS LEONCIO DA SILVA
1588,2019,RIO DE JANEIRO,33136670,CE GILDO CANDIDO DA SILVA
2959,2023,NITERÓI,33153795,COL DA POLICIA MILITAR DO EST DO RIO DE JANEIRO

In [27]:
df_join.to_csv(
    "/content/drive/MyDrive/matriculados_rendimentos_join2025.csv",
    index=False,
    encoding='utf-8-sig'
)

print("Arquivo final salvo!")

Arquivo final salvo!

In [21]:
df_join = pd.merge(
    matriculados,
    rendimentos,
    left_on=['Codigo_da_Escola', 'Ano_do_Censo'],
    right_on=['Codigo_Escola', 'Ano'],
    how='inner'
)

print("Resultado do JOIN:", len(df_join))

print(
    sorted(df_join['Ano_do_Censo'].unique())
)

Resultado do JOIN: 4009
[np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]