In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('matriculados_rendimentos_join_2025.csv')

In [ ]:
df_atualizado = df.drop(columns=['Ano', 'Municipio', 'Codigo_Escola', 'Escola', 'Dependencia', 'Dependencia_Administrativa'])

In [ ]:
df_atualizado.head(10)

,Ano_do_Censo,Nome_do_Municipio,Codigo_da_Escola,Nome_da_Escola,Quantidade_de_Matriculados_Ensino_Medio,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
0,2015,MARICÁ,33054215,CE EUCLYDES PAULO DA SILVA,211.0,72.2,21.7,6.1
1,2015,MARICÁ,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,400.0,86.6,9.1,4.3
2,2015,MARICÁ,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,516.0,87.2,8.8,4.0
3,2015,RIO DE JANEIRO,33067783,CE FRANCISCO CAMPOS,233.0,54.1,23.8,22.1
4,2015,RIO DE JANEIRO,33067252,INSTITUTO SUPERIOR DE EDUCACAO DO RIO DE JANEIRO,828.0,79.3,20.5,0.2
5,2015,RIO DE JANEIRO,33067228,ESCOLA TECNICA ESTADUAL FERREIRA VIANA,938.0,75.9,18.5,5.6
6,2015,RIO DE JANEIRO,33066620,CE SOARES PEREIRA,109.0,72.9,11.2,15.9
7,2015,RIO DE JANEIRO,33066612,CE PROFESSOR CLOVIS SALGADO,263.0,73.4,19.4,7.2
8,2015,RIO DE JANEIRO,33066590,CE ANTONIO PRADO JUNIOR,1634.0,82.1,16.0,1.9
9,2015,RIO DE JANEIRO,33066523,INSTITUTO DE APLICACAO FERNANDO RODRIGUES DA S...,281.0,97.4,2.6,0.0

In [ ]:
df_atualizado.tail(20)

,Ano_do_Censo,Nome_do_Municipio,Codigo_da_Escola,Nome_da_Escola,Quantidade_de_Matriculados_Ensino_Medio,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
3989,2025,SÃO GONÇALO,33096970,CIEP 309 ZUZU ANGEL BRASILCOLOMBIA,88.0,97.5,2.5,0.0
3990,2025,SÃO GONÇALO,33091897,CE CORONEL PM MARCUS JARDIM,235.0,99.6,0.4,0.0
3991,2025,SÃO GONÇALO,33091382,CE CORONEL FRANCISCO LIMA,181.0,99.4,0.0,0.6
3992,2025,SÃO GONÇALO,33091323,CE SUBTENENTE PM MARCO ANTONIO GRIPP,120.0,100.0,0.0,0.0
3993,2025,SÃO GONÇALO,33090831,CE DOM ANTONIO DE ALMEIDA MORAES JUNIOR,133.0,98.4,0.0,1.6
3994,2025,SÃO GONÇALO,33090327,CE DESEMBARGADOR FERREIRA PINTO,245.0,88.8,7.4,3.8
3995,2025,SÃO GONÇALO,33090688,CIEP 239 PROFESSORA ELZA VIANNA FIALHO,246.0,85.2,6.6,8.2
3996,2025,SÃO GONÇALO,33090670,CIEP 050 PABLO NERUDA,169.0,85.3,10.0,4.7
3997,2025,SÃO GONÇALO,33090653,CIEP 121 PROFESSOR JOADELIO CODECO,217.0,90.7,1.9,7.4
3998,2025,SÃO GONÇALO,33103925,CIEP 421 DEPUTADA CRISTINA TAVARES,63.0,96.8,3.2,0.0
3999,2025,SÃO GONÇALO,33090475,CE VITAL BRASIL,220.0,95.3,2.8,1.9
4000,2025,SÃO GONÇALO,33090459,CE PROFESSORA ODYSSEA SILVEIRA DE SIQUEIRA,146.0,97.7,2.3,0.0
4001,2025,SÃO GONÇALO,33089124,CE PADRE MANUEL DA NOBREGA,186.0,96.2,1.6,2.2
4002,2025,SÃO GONÇALO,33089108,CE PANDIA CALOGERAS,1065.0,89.3,9.7,1.0
4003,2025,SÃO GONÇALO,33089094,CE NILO PECANHA,813.0,92.8,4.7,2.5
4004,2025,SÃO GONÇALO,33089086,CE MINISTRO JOSE DE MOURA E SILVA,165.0,93.0,0.6,6.4
4005,2025,SÃO GONÇALO,33091340,CE CAPITAO OSWALDO ORNELLAS,297.0,93.9,1.3,4.8
4006,2025,SÃO GONÇALO,33091200,CE WALTER ORLANDINE,1081.0,96.6,2.8,0.6
4007,2025,SÃO GONÇALO,33091196,CE SANTOS DIAS,332.0,92.1,5.3,2.6
4008,2025,SÃO GONÇALO,33103909,CIEP 238 DOUTOR ILTON FARIA DA COSTA,240.0,92.3,5.1,2.6

In [ ]:
df_atualizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 8 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Ano_do_Censo                             4009 non-null   int64
 1   Nome_do_Municipio                        4009 non-null   object
 2   Codigo_da_Escola                         4009 non-null   int64
 3   Nome_da_Escola                           4009 non-null   object
 4   Quantidade_de_Matriculados_Ensino_Medio  4009 non-null   float64
 5   Aprovacao_EM_Total                       4009 non-null   float64
 6   Reprovacao_EM_Total                      4009 non-null   float64
 7   Abandono_EM_Total                        4009 non-null   float64
dtypes: float64(4), int64(2), object(2)
memory usage: 250.7+ KB

In [ ]:
df_modelo = df_atualizado.copy()

In [ ]:
df_modelo = df_modelo.sort_values(
    ['Codigo_da_Escola', 'Ano_do_Censo']
)
df_modelo.head()

,Ano_do_Censo,Nome_do_Municipio,Codigo_da_Escola,Nome_da_Escola,Quantidade_de_Matriculados_Ensino_Medio,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
990,2017,SÃO GONÇALO,33051879,CE DOUTOR MOACYR MEIRELLES PADILHA,584.0,69.9,19.2,10.9
1366,2018,SÃO GONÇALO,33051879,CE DOUTOR MOACYR MEIRELLES PADILHA,476.0,64.3,31.8,3.9
1714,2019,SÃO GONÇALO,33051879,CE DOUTOR MOACYR MEIRELLES PADILHA,435.0,70.4,16.7,12.9
2102,2020,SÃO GONÇALO,33051879,CE DOUTOR MOACYR MEIRELLES PADILHA,379.0,97.6,0.0,2.4
2481,2021,SÃO GONÇALO,33051879,CE DOUTOR MOACYR MEIRELLES PADILHA,382.0,94.3,5.2,0.5

In [ ]:
df_modelo.to_csv('tabela_final.csv', index=False)